spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - log-local
      dev:
        - db-dev
        - log-dev
    include:
      - db
      - log

logging:
  level:
    org.hibernate.SQL: debug